development:
  adapter: postgresql
  host: localhost
  database: 100k_dev
  username: John
  password:
  port:

test: &test
  adapter: mysql2
  host: localhost
  username: john
  password: password
  database: nytla_test

production:
  adapter: postgresql
  host: 69.55.62.19
  database: production
  username: postgres
  password:
